export const MockedPlayerDetails = {
  funcDisabled: {
    message: "disabled",
    kick: "disabled",
    warn: "disabled",
    ban: false,
  },
  id: false,
  license: "9b9fc300cc65d22ad3b536175a4d15c0e4933753",
  identifiers: [
    "license:9b9fc300cc65d22ad3b536175a4d15c0e4933753",
    "license2:9b9fc300cc65d22ad3b536175a4d15c0e4933753",
    "steam:765611981462241080",
    "xbl:2535431930771985",
    "live:914798250090349",
    "discord:188181246600282113",
    "fivem:226041",
  ],
  isTmp: false,
  name: "Soneca",
  actionHistory: [
    {
      id: "ADX9-C61Y",
      action: "BAN-REVOKED",
      date: "30/05",
      reason: "sdfsdfsdf",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "BPGZ-HL53",
      action: "WHITELIST-REVOKED",
      date: "30/05",
      reason: null,
      author: "tabarra",
      color: "dark",
    },
    {
      id: "W283-2H5W",
      action: "BAN-REVOKED",
      date: "30/05",
      reason: "efrdgdfdf",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "A4Q6-JF45",
      action: "WARN",
      date: "31/05",
      reason: "warningggggggggggg",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "AJH8-SYDZ",
      action: "BAN-REVOKED",
      date: "31/05",
      reason: "ban test",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "A3NS-NJQK",
      action: "BAN-REVOKED",
      date: "31/05",
      reason: "aaaaaaaaaaaaaaaaaa",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "AXE6-FU64",
      action: "WHITELIST-REVOKED",
      date: "14/06",
      reason: null,
      author: "tabarra",
      color: "dark",
    },
    {
      id: "WRFY-N3G6",
      action: "WARN",
      date: "14/06",
      reason: "🆃🆇🅰🅳🅼🅸🅽",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "BU6G-38ZF",
      action: "WHITELIST-REVOKED",
      date: "30/06",
      reason: null,
      author: "tabarra",
      color: "dark",
    },
    {
      id: "WQH8-283J",
      action: "WHITELIST-REVOKED",
      date: "30/06",
      reason: null,
      author: "tabarra",
      color: "dark",
    },
    {
      id: "A1VA-GPWH",
      action: "WHITELIST-REVOKED",
      date: "30/06",
      reason: null,
      author: "tabarra",
      color: "dark",
    },
    {
      id: "CTR-GNKD",
      action: "WARN",
      date: "30/06",
      reason: "zxc",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "B94D-F6H5",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "dsfdfs",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "W6S2-YAXW",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "sadf sadf asdf asd",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "BRS4-B8WH",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "msgmsgmsgmsg msg",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "WKRY-18W1",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "sdf sdf dsf ds",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "AV45-F3T3",
      action: "WHITELIST",
      date: "30/06",
      reason: null,
      author: "tabarra",
      color: "success",
    },
    {
      id: "WE3S-8L7F",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "asdasd",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "WCKP-B3FZ",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "sadf",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "BS18-56L9",
      action: "BAN-REVOKED",
      date: "30/06",
      reason: "zdfgdfg dfg dfg dfdfg",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "WQTN-QBPF",
      action: "WARN",
      date: "07/07",
      reason: "dfsg",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "BM1N-UZYT",
      action: "WARN",
      date: "07/07",
      reason: "fds",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "W37E-C7A4",
      action: "WARN-REVOKED",
      date: "07/07",
      reason: "sdf",
      author: "tabarra",
      color: "dark",
    },
    {
      id: "W9PM-8QFL",
      action: "WARN",
      date: "07/07",
      reason: "yuiyiu",
      author: "tabarra",
      color: "warning",
    },
    {
      id: "A5UN-9DDS",
      action: "BAN",
      date: "25/05",
      reason: "ssss",
      author: "tabarra",
      color: "danger",
    },
  ],
  joinDate: "May 30, 2020 - 01:27:49",
  sessionTime: "0 minutes",
  playTime: "1 hour, 57 minutes",
  notesLog: "",
  notes: "",
};
