name: Check Locale PR

on:
  pull_request:
    paths:
      - 'locale/**'

jobs:
  check-locale-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Enforce base branch
        shell: bash
        run: |
          BASE_BRANCH=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json baseRefName -q '.baseRefName')
          if [[ "$BASE_BRANCH" == "main" || "$BASE_BRANCH" == "master" ]]; then
            echo "Pull request is targeting the main branch. Please target a feature branch instead."
            exit 1
          fi
        
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run locale:check
        id: locale-check
        run: npm run locale:check
