name: Check Locale PR

on:
  pull_request:
    paths:
      - 'locale/**'

jobs:
  check-locale-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run locale:check
        id: locale-check
        run: npm run locale:check
